# permissions for end users to edit flinkjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flinkjob-editor-role
rules:
- apiGroups:
  - jobs.flink.stream.cluster
  resources:
  - flinkjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobs.flink.stream.cluster
  resources:
  - flinkjobs/status
  verbs:
  - get
