# permissions for end users to view flinkjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flinkjob-viewer-role
rules:
- apiGroups:
  - jobs.flink.stream.cluster
  resources:
  - flinkjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobs.flink.stream.cluster
  resources:
  - flinkjobs/status
  verbs:
  - get
